variables:
  GODEBUG: "http2client=0"
  RIG_R_VERSION: release #one of oldrel, next, release, devel
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  timeout: 8h 00m
  script:
    - /kaniko/executor
      --build-arg RIG_R_VERSION=${RIG_R_VERSION}
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/${RIG_R_VERSION}:latest"
  rules:
    - if: $RIG_R_VERSION == "release"
    - if: $RIG_R_VERSION == "oldrel"
    - if: $RIG_R_VERSION == "next"
    - if: $RIG_R_VERSION == "devel"

trigger_job:
  variables:
    RIG_R_VERSION: $RIG_R_VERSION
  trigger:
    include:
    - project: libreumg/internal/dataquier_builder
      ref: split-up
      file: '/.gitlab-ci.yml'


