variables:
  GODEBUG: "http2client=0"
build:
  stage: build
  tags:
    - scarab-buildkit-flags
  image:
    name: moby/buildkit:rootless
    entrypoint: [""]
  timeout: 8h 00m
  variables:
      BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > ~/.docker/config.json
  script:
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context="${CI_PROJECT_DIR}" \
        --local dockerfile="${CI_PROJECT_DIR}/Dockerfile" \
        --output type=image,name=$CI_REGISTRY_IMAGE:testing,push=true

trigger_job:
  trigger:
    project: libreumg/internal/dataquier_builder
